# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grosslyincandescent.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Grossly Incandescent
  avatar: avatar.png
  description: "Posts about programming, balance, tech and praise for the sun." # used by search engines

  # Header and footer text
  header_text:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "ckndlr@gmail.com"
  github: "cknadler"
  instagram: "cknadler"
  linkedin: "https://www.linkedin.com/profile/view?id=91399948"
  stack_exchange: "http://stackexchange.com/users/416318/chris-knadler"
  twitter: "cknadler"

  # Scripts
  google_analytics: "UA-37233322-2"
  disqus_shortname: "grosslyincandescent"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
